# Numpy Library




# importing the library

In [1]:
import numpy as np

# Numpy Arrays

In [2]:
my_list=[1,2,3,4,5]

In [3]:
arr=np.array(my_list)

In [4]:
arr

array([1, 2, 3, 4, 5])

# Matrix is a list of lists

In [5]:
mat=[[1,2,3],[4,5,6],[7,8,9]]

In [6]:
x=np.array(mat)

In [7]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# range in numpy

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

# to print array of zeroes 

In [10]:
# to print 1*3 array of zeroes
np.zeros(3)

array([0., 0., 0.])

In [11]:
#to print 5*5 array of zeroes
# must put 5,5 in () (tuple)
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# to print array of ones

In [12]:
# to print 1*n array 
# n=5
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
# to print m*n array 
#n=3,m=5
# must put 5,3 in () (tuple)
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Linspace function

In [14]:
#this function takes the start , end , num of iletrations and gives an array of numbers with values from start to the end 
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

# Eye Function

In [15]:
# eye function gives a square array its daigonals equal to 1 but the rest of the elements equal 0 
#this function takes a number that indicates number of rows and columns
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Random Functions

In [16]:
#this function returns an array of random values from 0 to 1
#this function takes the number of digits to be printed
np.random.rand(10)

array([0.35228541, 0.25402591, 0.22884245, 0.86567279, 0.86230279,
       0.8692695 , 0.83556778, 0.12246984, 0.82284376, 0.69397601])

In [17]:
#this function returns an array of random values 
np.random.randn(5)

array([ 0.73460236,  1.34193964,  0.35605103, -1.68861722,  0.36131043])

In [18]:
#this function returns an integer between 2 numbers
# this function takes start number and end number
np.random.randint(1,100)

75

# Reshape Function

In [19]:
# this function can change the shape of array from 1D to 2D or vice versa
arr=([1,2,3,4,5,6])
arr=np.array(arr)
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

# Max() and Min()

In [20]:
# to get the maximum value in an array
arr.max()

6

In [21]:
# to get the minimum value in an array
arr.min()

1

In [22]:
# to get the index of the maximum value in an array
arr.argmax()

5

In [23]:
# to get the index of the minimum value in an array
arr.argmin()

0

In [24]:
# attribute we use to know the shape of our array
arr.shape

(6,)

# Numpy Indexing & Selection

In [25]:
listl=[0,1,2,3,4,5,6,7,8,9,10]
arr=np.array(listl)

In [26]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# to select a specific value we pass the index in [] 
arr[7]

7

In [28]:
# to select some values we pass startindex : endindex in []
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [29]:
arr[1:5]

array([1, 2, 3, 4])

In [30]:
# when we want from index 0 we may not write 0 in []
# o/p is like the 28 cell
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [31]:
# when we want to get the numbers from a specific index to the end 
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

# Referencing to an array  

In [32]:
# referencing: take some of elements and put them in another array
# when we make any change in the other array , this change will happen in the original array 

In [33]:
part_of_arr=arr[:5]

In [34]:
part_of_arr[:]=100

In [35]:
part_of_arr

array([100, 100, 100, 100, 100])

In [36]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

# Copying from an array 

In [37]:
# to make another array with the same elements of the original we have function copy() 

arr_copy = arr.copy()

In [38]:
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [39]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

# 2D Array : Selecting an element from 2D Array

In [40]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [41]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [42]:
arr_2d[0][0]

5

In [43]:
arr_2d[2][1]

40

# 2D Array : Selecting asubsection from 2D Array

In [44]:
# to determine specific rows and specific columns
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [45]:
arr_2d[:1,1:]

array([[10, 15]])

# Selection based on the values 

In [46]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [47]:
bool_arr = [arr<10]

In [48]:
# it is an array whose values are boolean based on the condition we made 
bool_arr

[array([False, False, False, False, False,  True,  True,  True,  True,
         True, False])]

In [49]:
# to get the values based on the condition 
arr[arr<10]

array([5, 6, 7, 8, 9])

# Numpy Operations

In [50]:
# Adding 
arr=arr+arr

In [51]:
arr


array([200, 200, 200, 200, 200,  10,  12,  14,  16,  18,  20])

In [52]:
arr+3

array([203, 203, 203, 203, 203,  13,  15,  17,  19,  21,  23])

In [53]:
# sutracting
arr - 4

array([196, 196, 196, 196, 196,   6,   8,  10,  12,  14,  16])

In [54]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
# Multiplication
arr * arr

array([40000, 40000, 40000, 40000, 40000,   100,   144,   196,   256,
         324,   400])

In [56]:
arr * 2

array([400, 400, 400, 400, 400,  20,  24,  28,  32,  36,  40])

In [57]:
# Division
arr / 2

array([100., 100., 100., 100., 100.,   5.,   6.,   7.,   8.,   9.,  10.])

In [62]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# mathematical operations

In [59]:
np.sin(arr)

array([-0.8732973 , -0.8732973 , -0.8732973 , -0.8732973 , -0.8732973 ,
       -0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725,
        0.91294525])

In [60]:
np.log(arr)

array([5.29831737, 5.29831737, 5.29831737, 5.29831737, 5.29831737,
       2.30258509, 2.48490665, 2.63905733, 2.77258872, 2.89037176,
       2.99573227])

In [61]:
np.exp(arr)

array([7.22597377e+86, 7.22597377e+86, 7.22597377e+86, 7.22597377e+86,
       7.22597377e+86, 2.20264658e+04, 1.62754791e+05, 1.20260428e+06,
       8.88611052e+06, 6.56599691e+07, 4.85165195e+08])